# Fill in with your details

name = "tg-bog-nails"
main = "src/index.ts"
compatibility_date = "#" 
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB" #
database_name = "#" 
database_id = "#" 
migrations_dir = "./migrations"

[vars]
TELEGRAM_BOT_TOKEN = "#"

[observability.logs]
enabled = true
