name = "tg-bog-nails"
main = "src/index.ts"
compatibility_date = "2024-08-21" # Совместимая дата
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB" #
database_name = "salon_db" 
database_id = "0d319bb0-a720-449b-9ad1-5f99a98c2c1d" 
migrations_dir = "./migrations"

[vars]
TELEGRAM_BOT_TOKEN = "7688065241:AAGQSW5Ut9aAmReGhWaUPPndK8rMcOjouQk"

[observability.logs]
enabled = true
